const firebaseUserDummy: firebase.User = {
    delete: null,
    emailVerified: null,
    getIdTokenResult: null,
    getIdToken: null,
    isAnonymous: null,
    linkAndRetrieveDataWithCredential: null,
    linkWithCredential: null,
    linkWithPhoneNumber: null,
    linkWithPopup: null,
    linkWithRedirect: null,
    metadata: null,
    phoneNumber: null,
    providerData: null,
    reauthenticateAndRetrieveDataWithCredential: null,
    reauthenticateWithCredential: null,
    reauthenticateWithPhoneNumber: null,
    reauthenticateWithPopup: null,
    reauthenticateWithRedirect: null,
    refreshToken: null,
    reload: null,
    sendEmailVerification: null,
    toJSON: null,
    unlink: null,
    updateEmail: null,
    updatePassword: null,
    updatePhoneNumber: null,
    updateProfile: null,
    displayName: null,
    email: null,
    photoURL: null,
    providerId: null,
    uid: null,
};

export { firebaseUserDummy };
